import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import Header from "./components/Header";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loading from "./loading";
export const metadata: Metadata = {
  title: "StackSnap",
  description: "Generated by create next app",
  icons: {
    icon: "/StackOverflow.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
        <Toaster position="bottom-right" reverseOrder={false} />
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
